host:
  server_address: "0.0.0.0:8080"
  base_url: "https://example.com"
  cert_file: "/etc/ssl/certs/server.crt"
  key_file: "/etc/ssl/private/server.key"

postgres:
  database_dsn: "postgres://esharipov:password@localhost:5432/puppies?sslmode=disable"

mongo:
  mongo_dsn: "mongodb://localhost:27017"

redis:
  database_redisAddress: "localhost:6379"
  database_redisPassword: ""
  database_RedisDBName: 0

s3:
  s3_url: "https://s3.cloud.ru"
  s3_region: "ru-central1"
  s3_access_key: "YOUR_ACCESS_KEY"
  s3_secret_key: "YOUR_SECRET_KEY"
  s3_bucket: "puppies-images"